services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Exposing Next.js app on port 3000
    networks:
      - luminor_network

networks:
  luminor_network:
    driver: bridge
